Name:           ros-hydro-abb-irb6640-moveit-config
Version:        1.1.5
Release:        0%{?dist}
Summary:        ROS abb_irb6640_moveit_config package

Group:          Development/Libraries
License:        BSD
URL:            http://ros.org/wiki/abb_irb6640_moveit_config
Source0:        %{name}-%{version}.tar.gz

BuildArch:      noarch

Requires:       ros-hydro-abb-irb6600-support
Requires:       ros-hydro-industrial-robot-simulator
Requires:       ros-hydro-joint-state-publisher
Requires:       ros-hydro-moveit-planners-ompl
Requires:       ros-hydro-moveit-ros-move-group
Requires:       ros-hydro-moveit-ros-visualization
Requires:       ros-hydro-moveit-simple-controller-manager
Requires:       ros-hydro-robot-state-publisher
Requires:       ros-hydro-xacro
BuildRequires:  ros-hydro-catkin

%description
MoveIt package for the ABB IRB 6640. An automatically generated package with
all the configuration and launch files for using the ABB IRB 6640 with the
MoveIt Motion Planning Framework.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/hydro/setup.sh" ]; then . "/opt/ros/hydro/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/hydro" \
        -DCMAKE_PREFIX_PATH="/opt/ros/hydro" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/hydro/setup.sh" ]; then . "/opt/ros/hydro/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/hydro

%changelog
* Tue Mar 17 2015 Shaun Edwards (Southwest Research Institute) <sedewards@swri.org> - 1.1.5-0
- Autogenerated by Bloom

* Sat Dec 27 2014 Shaun Edwards (Southwest Research Institute) <sedewards@swri.org> - 1.1.4-0
- Autogenerated by Bloom

